version: "3.9"

services:
  backend:
    build: ./backend
    container_name: statuspulse_backend
    ports:
      - "8081:8000"
    volumes:
      - ./data:/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: statuspulse_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: unless-stopped

volumes:
  data:
    driver: local
